
name: hello world CI/CD
on:
  push:
    branches: [ master ]

jobs:
  build-and-push-dev:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4        # grab code + committed Dockerfile

    - name: Login to JFrog Docker registry
      run: echo "${{ secrets.JFROG_PASSWORD }}" | docker login accenture2026.jfrog.io --username ${{ secrets.JFROG_USERNAME }} --password-stdin

    - name: Build image
      run: docker build -t hello_world:latest .

    - name: Compute short SHA tag
      id: set_tag
      run: echo "TAG=${GITHUB_SHA::7}" >> "$GITHUB_ENV"

    - name: Tag for JFrog dev repo
      run: docker tag hello_world:latest accenture2026.jfrog.io/docker-2026-docker/hello_world:dev-${TAG}

    - name: Push to dev repo
      run: docker push accenture2026.jfrog.io/docker-2026-docker/hello_world:dev-${TAG}

    - name: Install JFrog CLI & configure
      run: |
        curl -fL https://install-cli.jfrog.io | sh
        jf config add jfrog-server --url=https://accenture2026.jfrog.io --user=${{ secrets.JFROG_USERNAME }} --password=${{ secrets.JFROG_PASSWORD }}

    - name: Publish build info
      env:
        BUILD_NAME: hello_world-ci
        BUILD_NUMBER: ${{ env.TAG }}
      run: |
        jf rt docker-push accenture2026.jfrog.io/docker-2026-docker/hello_world:dev-${TAG} docker-dev --build-name=$BUILD_NAME --build-number=$BUILD_NUMBER
        jf rt build-collect-env $BUILD_NAME $BUILD_NUMBER
        jf rt build-publish $BUILD_NAME $BUILD_NUMBER
